### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by gyzhang123** [subho406/OmniNet#2]
when running
"
python predict.py model.pth vqa --image sample_data/kids-hand-signals.jpg --text "What is the kid driving?"
"
got a error:
"
 File "/home/gy/OmniNet-master/libs/omninet/cnp/cnp.py", line 198, in encode
    self.pad_cache=torch.cat((self.pad_cache,pad_mask),1)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 1 in sequence argument at position #1 'tensors'
"
so how can I solve this problem ?

**Comment by gyzhang123** [comment]
i solved it by 
"
$ conda env create -f environment.yml
$ source activate omninet
"
still not find out a reason.--

**Comment by subho406** [comment]
Issue is caused when predict.py is run using older version of Pytorch. The supported Pytorch version is >=1.0.1.

**Comment by qaazii** [comment]
I still have the problem. I am using pytorch==1.4.0 and also applied this 

"i solved it by
"
$ conda env create -f environment.yml
$ source activate omninet
"
still not find out a reason.--""

any comments please.

**Comment by qaazii** [comment]
didnt find any solution for this. tries alot of versions. there no error with libraries.
