### ISSUE TITLE
The website is broken on pretrained model

### ISSUE THREAD

**Issue by jkllbn2563** [subho406/OmniNet#5]
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 834945753818 is disabled in state delinquent
</Details>
</Error>

**Comment by subho406** [comment]
Hi, thanks for notifying this. Completed all pending billings. Should be resolved soon.

**Comment by subho406** [comment]
The issue has been resolved.
